#!/usr/bin/env python3
"""Generate every results table of the DMKD manuscript from the campaign data.

Reads results/dmkd_campaign/analysis.json (written by dmkd_analysis.py), the
unit JSONs and the external-baseline JSONs; writes paper_prai/tables/gen_*.tex.
Each file carries a %% GENERATED header; never edit the numbers by hand --
re-run this script. Missing cells print as "--".

Usage: python scripts/dmkd_tables.py
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "scripts"))
sys.path.insert(0, ROOT)
import dmkd_analysis as A  # noqa: E402

CAMP = os.path.join(ROOT, "results", "dmkd_campaign")
OUT = os.path.join(ROOT, "paper_prai", "tables")

NAMES = {"miml_lcga": "LCGA", "abmil_ml": "ABMIL-ML",
         "transformer_pool_ml": "Transformer-Pool", "mlp_pool_ml": "MLP-Pool",
         "clam_multilabel_ml": "CLAM-ML", "moe_k4": "LCGA-MoE",
         "lcga_attn128": "LCGA-wide"}
SHORTN = {"miml_lcga": "LCGA", "abmil_ml": "ABMIL-ML", "transformer_pool_ml": "T-Pool",
          "mlp_pool_ml": "MLP-Pool", "clam_multilabel_ml": "CLAM-ML"}
OBJN = {"bce": "BCE", "rankasl": "Rank+ASL"}
DSN = {"scene": "Scene", "reuters": "Reuters", "mscv2": "MSCV2",
       "letter_frost": "Letter Frost", "letter_carroll": "Letter Carroll",
       "yeast": "Yeast", "birdsong": "Birdsong",
       "protein_haloarcula": "Prot.\\ Haloarcula", "protein_pyrococcus": "Prot.\\ Pyrococcus",
       "protein_geobacter": "Prot.\\ Geobacter", "protein_azotobacter": "Prot.\\ Azotobacter",
       "emotions": "Emotions", "medical": "Medical"}
MSHORT = {"HammingLoss": "HL", "OneError": "OE", "Coverage": "Cov",
          "RankingLoss": "RL", "AveragePrecision": "AP"}
EXT = {"miml_knn": "\\textsc{Miml-kNN}", "mlknn_hausdorff": "ML-kNN",
       "br_bagmean": "BR-LR"}


def header(src):
    return (f"%% GENERATED by scripts/dmkd_tables.py from {src}.\n"
            "%% Do not edit numbers by hand; re-run the script.\n")


def fmt(x, nd=3):
    return "--" if x is None else f"{x:.{nd}f}"


def fmt_p(p):
    if p is None:
        return "--"
    return "$<$0.001" if p < 0.001 else f"{p:.3f}"


def write(name, body):
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, name), "w") as fh:
        fh.write(body)


def t_objective(an):
    rows = []
    for a in A.FIVE:
        cells = []
        for m in ("AveragePrecision", "RankingLoss"):
            t = an["A1_objective"][m][a]
            wins = (f"{t.get('wins_a', '--')}/{t.get('wins_b', '--')}"
                    if t.get("p") is not None else "--")
            cells += [fmt(t.get("median_diff"), 4), wins, fmt_p(t.get("p_holm"))]
        n = an["A1_objective"]["AveragePrecision"][a]["n"]
        rows.append(f"{NAMES[a]} & {n} & " + " & ".join(cells) + " \\\\")
    body = header("analysis.json:A1_objective") + r"""\begin{table}[t]
\centering
\caption{A1 -- objective effect. Rank+ASL versus BCE per architecture: median over datasets of the paired difference in seed-mean metric (positive = Rank+ASL better), datasets won/lost by Rank+ASL, and Holm-adjusted Wilcoxon $p$ (over the five architectures). $n$ = datasets with all ten runs complete.}
\label{tab:objective}
\footnotesize
\begin{tabular}{@{}lr rrr rrr@{}}
\toprule
 & & \multicolumn{3}{c}{Average Precision} & \multicolumn{3}{c}{Ranking Loss} \\
\cmidrule(lr){3-5}\cmidrule(l){6-8}
Architecture & $n$ & median $\Delta$ & W/L & $p_{\mathrm{Holm}}$ & median $\Delta$ & W/L & $p_{\mathrm{Holm}}$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_objective.tex", body)


def t_architecture(an):
    rows = []
    for a in A.FIVE:
        cells = []
        for o in A.OBJS:
            for m in ("AveragePrecision", "RankingLoss"):
                r = an["A2_architecture"].get(f"{o}/{m}", {})
                cells.append(fmt(r.get("avg_rank", {}).get(a), 2))
        rows.append(f"{NAMES[a]} & " + " & ".join(cells) + " \\\\")
    fr = []
    for o in A.OBJS:
        for m in ("AveragePrecision", "RankingLoss"):
            r = an["A2_architecture"].get(f"{o}/{m}", {})
            fr.append(fmt_p(r.get("friedman_p")))
    ns = [an["A2_architecture"].get(f"{o}/AveragePrecision", {}).get("n") for o in A.OBJS]
    body = header("analysis.json:A2_architecture") + r"""\begin{table}[t]
\centering
\caption{A2 -- architecture effect. Average rank of each architecture over datasets (1 = best) on seed-mean Average Precision and Ranking Loss, separately under each objective, and the Friedman $p$-value for no difference among the five. $n=""" + "/".join(str(x) for x in ns) + r"""$ datasets (BCE/Rank+ASL).}
\label{tab:architecture}
\footnotesize
\begin{tabular}{@{}l rr rr@{}}
\toprule
 & \multicolumn{2}{c}{BCE} & \multicolumn{2}{c}{Rank+ASL} \\
\cmidrule(lr){2-3}\cmidrule(l){4-5}
Architecture & AP & RL & AP & RL \\
\midrule
""" + "\n".join(rows) + r"""
\midrule
Friedman $p$ & """ + " & ".join(fr) + r""" \\
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_architecture.tex", body)


def t_ensemble(an):
    rows = []
    for a in A.FIVE:
        cells = []
        for o in A.OBJS:
            t = an["A3_ensemble"]["AveragePrecision"][f"{a}/{o}"]
            wins = (f"{t.get('wins_a', '--')}/{t.get('wins_b', '--')}"
                    if t.get("p") is not None else "--")
            cells += [fmt(t.get("median_diff"), 4), wins, fmt_p(t.get("p_holm"))]
        rows.append(f"{NAMES[a]} & " + " & ".join(cells) + " \\\\")
    body = header("analysis.json:A3_ensemble") + r"""\begin{table}[t]
\centering
\caption{A3 -- ensembling. 5-seed ensemble versus the seed-mean single model of the same architecture and objective, Average Precision: median paired gain over datasets, datasets improved/worsened, Holm-adjusted Wilcoxon $p$ (over the ten configurations).}
\label{tab:ensemble}
\footnotesize
\begin{tabular}{@{}l rrr rrr@{}}
\toprule
 & \multicolumn{3}{c}{BCE} & \multicolumn{3}{c}{Rank+ASL} \\
\cmidrule(lr){2-4}\cmidrule(l){5-7}
Architecture & median gain & W/L & $p_{\mathrm{Holm}}$ & median gain & W/L & $p_{\mathrm{Holm}}$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_ensemble.tex", body)


def t_variance(an):
    rows = []
    keys = ("architecture", "objective", "architecture_x_objective", "seed_residual")
    for m in A.METRICS:
        v = an["A4_variance"][m]
        sh, vc = v.get("share", {}), v.get("vc_share", {})
        rows.append(f"{MSHORT[m]} & {v.get('n_datasets', 0)} & "
                    + " & ".join(fmt(100 * sh[k], 0) if k in sh else "--" for k in keys) + " & "
                    + " & ".join(fmt(100 * vc[k], 0) if k in vc else "--" for k in keys)
                    + " \\\\")
    body = header("analysis.json:A4_variance") + r"""\begin{table}[t]
\centering
\caption{A4 -- where the variation comes from, over the four non-branching architectures $\times$ two objectives $\times$ five seeds, datasets as blocks. Left (pre-registered): share (\%) of the within-dataset sum of squares. Because the factors have very different degrees of freedom per dataset (architecture 3, objective 1, interaction 3, seed 32), sum-of-squares shares overstate the seed. Right (added after the campaign): share (\%) of the variance components estimated from the expected mean squares of the balanced crossed design, negative estimates set to zero.}
\label{tab:variance}
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{@{}lr rrrr rrrr@{}}
\toprule
 & & \multicolumn{4}{c}{Sum-of-squares share (pre-reg.)} & \multicolumn{4}{c}{Variance-component share} \\
\cmidrule(lr){3-6}\cmidrule(l){7-10}
Metric & $n$ & Arch. & Obj. & A$\times$O & Seed & Arch. & Obj. & A$\times$O & Seed \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_variance.tex", body)


def t_effects_perdataset(cells, an):
    """Pre-registered A4 side-by-side: per dataset, AP architecture spread
    (core four, and with CLAM-ML), objective gap per core architecture, and
    ensemble gain range."""
    pdx = an["A4_per_dataset"]
    rows = []
    for ds in A.DATASETS:
        r = pdx.get(ds, {})
        spread5 = []
        for o in A.OBJS:
            ms = [A.seed_table(cells, a, o, "AveragePrecision").get(ds) for a in A.FIVE]
            spread5.append(None if not all(ms) else max(m[0] for m in ms) - min(m[0] for m in ms))
        og = r.get("objective_gap", {})
        eg = [g for k, g in r.get("ensemble_gain", {}).items() if k.split("/")[0] in A.CORE]
        rows.append(f"{DSN[ds]} & {fmt(r.get('arch_spread_bce'))} & {fmt(r.get('arch_spread_rankasl'))} & "
                    f"{fmt(spread5[0])} & {fmt(spread5[1])} & "
                    f"{fmt(min(og.values()) if og else None)}--{fmt(max(og.values()) if og else None)} & "
                    f"{fmt(min(eg) if eg else None)}--{fmt(max(eg) if eg else None)} \\\\")
    body = header("analysis.json:A4_per_dataset + unit JSONs") + r"""\begin{table}[p]
\centering
\caption{A4, per dataset (Average Precision): spread between the best and worst seed-mean architecture under each objective, over the four non-branching architectures and over all five; range over the four non-branching architectures of the objective gap (Rank+ASL minus BCE); and range of the 5-seed ensemble gain over those four architectures and both objectives.}
\label{tab:effects-pd}
\footnotesize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}l rr rr cc@{}}
\toprule
 & \multicolumn{2}{c}{Spread, 4 arch.} & \multicolumn{2}{c}{Spread, 5 arch.} & Objective gap & Ensemble gain \\
\cmidrule(lr){2-3}\cmidrule(lr){4-5}
Dataset & BCE & R+A & BCE & R+A & range & range \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_effects_perdataset.tex", body)


def t_external_full(an):
    """A6 in full: per dataset and metric, how many of the ten neural
    configurations (seed-mean single model) each reference learner beats."""
    a6 = an["A6_external"]
    rows = []
    for ds in A.DATASETS:
        if ds not in a6:
            continue
        confs = a6[ds]
        cells_ = []
        for ext in EXT:
            for m in A.METRICS:
                n_better = sum(1 for c in confs if ext in confs[c] and not confs[c][ext][m]["neural_better"])
                cells_.append(str(n_better))
        rows.append(f"{DSN[ds]} & " + " & ".join(cells_) + " \\\\")
    mh = " & ".join(MSHORT[m] for m in A.METRICS)
    body = header("analysis.json:A6_external") + r"""\begin{table}[p]
\centering
\caption{A6 in full: for each reference learner, dataset and metric, the number of the ten neural configurations (five architectures $\times$ two objectives, seed-mean single models) that the reference learner matches or beats. 10 means it is at least as good as every neural configuration; 0 means every neural configuration is better.}
\label{tab:external-full}
\scriptsize
\setlength{\tabcolsep}{2.5pt}
\begin{tabular}{@{}l ccccc ccccc ccccc@{}}
\toprule
 & \multicolumn{5}{c}{""" + list(EXT.values())[0] + r"""} & \multicolumn{5}{c}{""" + list(EXT.values())[1] + r"""} & \multicolumn{5}{c}{""" + list(EXT.values())[2] + r"""} \\
\cmidrule(lr){2-6}\cmidrule(lr){7-11}\cmidrule(l){12-16}
Dataset & """ + mh + " & " + mh + " & " + mh + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_external_full.tex", body)


def t_moe(an):
    labels = {"K4_vs_K1_bce": "LCGA-MoE vs LCGA (BCE)",
              "K4_vs_K1_rankasl": "LCGA-MoE vs LCGA (Rank+ASL)",
              "K4_vs_attn128_rankasl": "LCGA-MoE vs LCGA-wide (Rank+ASL)"}
    rows = []
    for k, lab in labels.items():
        t = an["A5_moe"]["AveragePrecision"][k]
        wins = (f"{t.get('wins_a', '--')}/{t.get('wins_b', '--')}"
                if t.get("p") is not None else "--")
        rows.append(f"{lab} & {t['n']} & {fmt(t.get('median_diff'), 4)} & {wins} & "
                    f"{fmt_p(t.get('p_holm'))} \\\\")
    body = header("analysis.json:A5_moe") + r"""\begin{table}[t]
\centering
\caption{A5 -- does routing labels to attention experts help? Paired comparisons over datasets of seed-mean Average Precision (positive = first model better); Holm over the three.}
\label{tab:moe}
\footnotesize
\begin{tabular}{@{}lrrrr@{}}
\toprule
Comparison & $n$ & median $\Delta$AP & W/L & $p_{\mathrm{Holm}}$ \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_moe.tex", body)


def t_external(cells, an):
    """AP per dataset: best neural configuration (seed-mean single model, the
    pre-registered A6 comparison) and best neural 5-seed ensemble (added post
    hoc), against the three reference learners. Also writes counts as macros."""
    import glob
    ext = {}
    for p in glob.glob(os.path.join(CAMP, "external", "external_baselines_*.json")):
        for k, c in json.load(open(p)).items():
            if isinstance(c, dict) and "summary" in c:
                ext.setdefault(c["dataset"], {})[c["model"]] = c["summary"]
    ens = an.get("ensemble_cells", {})
    FRAMED = {"yeast", "emotions", "medical"}
    rows, n_ds, beat_single, beat_ens, names_ens = [], 0, 0, 0, []
    cnt = {"native": [0, 0, 0, []], "framed": [0, 0, 0, []]}   # n, single, ens, names(single)
    for ds in A.DATASETS:
        if ds not in ext:
            continue
        n_ds += 1
        best, who = None, None
        for a in A.FIVE:
            for o in A.OBJS:
                s_ = A.seed_table(cells, a, o, "AveragePrecision").get(ds)
                if s_ and (best is None or s_[0] > best):
                    best, who = s_[0], f"{SHORTN[a]}/{OBJN[o]}"
        be = max((v["AveragePrecision"] for k, v in ens.items()
                  if k.endswith("/" + ds) and k.split("/")[0] in A.FIVE), default=None)
        e = [ext[ds].get(m, {}).get("AveragePrecision", [None])[0] for m in EXT]
        emax = max(x for x in e if x is not None)
        beat_single += emax >= best
        grp = "framed" if ds in FRAMED else "native"
        cnt[grp][0] += 1
        if emax >= best:
            cnt[grp][1] += 1
            cnt[grp][3].append(f"{DSN[ds]} ({emax - best:+.3f})")
        if be is not None and emax >= be:
            beat_ens += 1
            names_ens.append(DSN[ds])
            cnt[grp][2] += 1
        allv = [v for v in [best, be] + e if v is not None]
        top = max(allv)
        f = lambda v: "--" if v is None else (f"\\textbf{{{v:.3f}}}" if v == top else f"{v:.3f}")
        rows.append(f"{DSN[ds]} & {f(best)} & {who or '--'} & {f(be)} & " + " & ".join(f(v) for v in e) + " \\\\")
    body = header("unit JSONs + analysis.json:ensemble_cells + results/dmkd_campaign/external") + r"""\begin{table}[t]
\centering
\caption{A6 -- neural models against non-neural reference learners on all thirteen benchmarks (the pre-registration covered the eight without a comparator under our folds; the other five were added after the campaign). Average Precision of the best neural single-model configuration (seed-mean; the pre-registered comparison), of the best neural 5-seed ensemble (added after the campaign), and of the three reference learners on identical folds. The neural columns are maxima over ten configurations chosen after the fact, which favours the neural side. Best per row in bold.}
\label{tab:external}
\footnotesize
\setlength{\tabcolsep}{3.5pt}
\begin{tabular}{@{}l rl r rrr@{}}
\toprule
 & \multicolumn{2}{c}{Best neural single} & Best neural & & & \\
Dataset & AP & configuration & ensemble & """ + " & ".join(EXT.values()) + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    write("gen_external.tex", body)
    return {"n": n_ds, "single": beat_single, "ens": beat_ens, "ens_names": names_ens, "groups": cnt}


def t_perdataset(cells, an):
    """Appendix: seed-mean (sd) of every architecture x objective, per metric."""
    parts = []
    order = ["AveragePrecision", "RankingLoss", "Coverage", "OneError", "HammingLoss"]
    longname = {"AveragePrecision": "Average Precision", "RankingLoss": "Ranking Loss",
                "Coverage": "Coverage", "OneError": "One-Error", "HammingLoss": "Hamming Loss"}
    for m in order:
        for o in A.OBJS:
            rows = []
            for ds in A.DATASETS:
                vals = []
                for a in A.FIVE:
                    s = A.seed_table(cells, a, o, m).get(ds)
                    nd = 2 if m == "Coverage" else 3
                    vals.append("--" if not s else f"{s[0]:.{nd}f} ({s[1]:.{nd}f})")
                rows.append(f"{DSN[ds]} & " + " & ".join(vals) + " \\\\")
            arrow = "$\\uparrow$" if m in A.HIGHER_BETTER else "$\\downarrow$"
            parts.append(r"""\begin{table}[p]
\centering
\caption{""" + f"{longname[m]} {arrow}, {OBJN[o]}" + r""": seed-mean over five seeds (across-seed sd) of the cross-validated single-model value.}
\label{tab:pd-""" + f"{MSHORT[m]}-{o}" + r"""}
\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}l rrrrr@{}}
\toprule
Dataset & """ + " & ".join(SHORTN[a] for a in A.FIVE) + r""" \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")
    write("gen_perdataset.tex", header("unit JSONs") + "\n".join(parts))


def t_numbers(an, cells, ext_counts=None):
    """Every number the prose cites, as LaTeX macros (\\dk...), so the text
    never carries a hand-typed value. Missing values render as a red '??'."""
    import numpy as np
    M = {}
    miss = r"\textcolor{red}{??}"
    def put(name, val, nd=3, pct=False):
        if val is None:
            M[name] = miss
        elif isinstance(val, str):
            M[name] = val
        elif pct:
            M[name] = f"{100 * val:.0f}"
        elif isinstance(val, (int, np.integer)):
            M[name] = str(int(val))
        else:
            M[name] = f"{val:.{nd}f}"
    tag = {"miml_lcga": "Lcga", "abmil_ml": "Abmil", "transformer_pool_ml": "Tpool",
           "mlp_pool_ml": "Mlp", "clam_multilabel_ml": "Clam"}
    mtag = {"AveragePrecision": "AP", "RankingLoss": "RL", "OneError": "OE",
            "Coverage": "Cov", "HammingLoss": "HL"}
    # A1
    for m, mt in mtag.items():
        n_rej = 0
        for a in A.FIVE:
            t = an["A1_objective"][m][a]
            put(f"dkObj{mt}Win{tag[a]}", t.get("wins_a"))
            put(f"dkObj{mt}Loss{tag[a]}", t.get("wins_b"))
            put(f"dkObj{mt}Med{tag[a]}", t.get("median_diff"), 4)
            put(f"dkObj{mt}P{tag[a]}", None if t.get("p_holm") is None else fmt_p(t["p_holm"]))
            if a in A.CORE and t.get("p_holm") is not None and t["p_holm"] < 0.05 \
                    and (t.get("median_diff") or 0) > 0:
                n_rej += 1
        put(f"dkObj{mt}NRejCore", n_rej)
    # A2
    for o in A.OBJS:
        for m, mt in mtag.items():
            r = an["A2_architecture"].get(f"{o}/{m}", {})
            put(f"dkFried{mt}{o.capitalize()}", None if r.get("friedman_p") is None else fmt_p(r["friedman_p"]))
            for a in A.FIVE:
                put(f"dkRank{mt}{o.capitalize()}{tag[a]}", r.get("avg_rank", {}).get(a), 2)
    # A2 post-hoc (Nemenyi, only where Friedman rejected)
    for o in A.OBJS:
        for m, mt in mtag.items():
            r = an["A2_architecture"].get(f"{o}/{m}", {})
            pairs = r.get("nemenyi_significant_pairs")
            put(f"dkNemCD{mt}{o.capitalize()}", r.get("nemenyi_cd"), 2)
            if pairs is None:
                put(f"dkNem{mt}{o.capitalize()}", "no post-hoc test (Friedman did not reject)")
            elif not pairs:
                put(f"dkNem{mt}{o.capitalize()}", "no pair differs by more than the critical difference")
            else:
                by_worse = {}
                for b, w, _ in pairs:
                    by_worse.setdefault(w, []).append(NAMES[b])
                txt = "; ".join(f"{NAMES[w]} ranks worse than " + ", ".join(sorted(bs))
                                for w, bs in by_worse.items())
                put(f"dkNem{mt}{o.capitalize()}", txt)
    # A3
    for o in A.OBJS:
        g = [an["A3_ensemble"]["AveragePrecision"][f"{a}/{o}"].get("median_diff") for a in A.FIVE]
        gc = [x for a, x in zip(A.FIVE, g) if a in A.CORE and x is not None]
        put(f"dkEnsMin{o.capitalize()}", min(gc) if gc else None, 3)
        put(f"dkEnsMax{o.capitalize()}", max(gc) if gc else None, 3)
        ps = [an["A3_ensemble"]["AveragePrecision"][f"{a}/{o}"].get("p_holm") for a in A.FIVE]
        ps = [x for x in ps if x is not None]
        put(f"dkEnsPmax{o.capitalize()}", fmt_p(max(ps)) if ps else None)
        for a in A.FIVE:
            t = an["A3_ensemble"]["AveragePrecision"][f"{a}/{o}"]
            put(f"dkEnsMed{o.capitalize()}{tag[a]}", t.get("median_diff"), 3)
            put(f"dkEnsWin{o.capitalize()}{tag[a]}", t.get("wins_a"))
    # A4
    for m, mt in mtag.items():
        sh = an["A4_variance"][m].get("share", {})
        for k, kt in (("architecture", "Arch"), ("objective", "Obj"),
                      ("architecture_x_objective", "Int"), ("seed_residual", "Seed")):
            put(f"dkVar{mt}{kt}", sh.get(k), pct=True)
            put(f"dkVc{mt}{kt}", an["A4_variance"][m].get("vc_share", {}).get(k), pct=True)
    pdx = an["A4_per_dataset"]
    for o in A.OBJS:
        sp = [v[f"arch_spread_{o}"] for v in pdx.values() if f"arch_spread_{o}" in v]
        eg = [g for v in pdx.values() for k, g in v.get("ensemble_gain", {}).items()
              if k.endswith("/" + o) and k.split("/")[0] in A.CORE]
        put(f"dkSpread{o.capitalize()}", float(np.median(sp)) if sp else None, 3)
        put(f"dkGain{o.capitalize()}", float(np.median(eg)) if eg else None, 3)
    og = [g for v in pdx.values() for a, g in v.get("objective_gap", {}).items()]
    put("dkObjGapMed", float(np.median(og)) if og else None, 4)
    for o in A.OBJS:
        sp5 = []
        for ds in A.DATASETS:
            ms = [A.seed_table(cells, a, o, "AveragePrecision").get(ds) for a in A.FIVE]
            if all(ms):
                sp5.append(max(m[0] for m in ms) - min(m[0] for m in ms))
        put(f"dkSpreadFive{o.capitalize()}", float(np.median(sp5)) if sp5 else None, 3)
    for a in A.FIVE:
        b = A.seed_table(cells, a, "bce", "AveragePrecision")
        r = A.seed_table(cells, a, "rankasl", "AveragePrecision")
        n_big = sum(1 for ds in b if ds in r and
                    abs(r[ds][0] - b[ds][0]) > np.sqrt((b[ds][1] ** 2 + r[ds][1] ** 2) / 2))
        put(f"dkObjBigN{tag[a]}", n_big)
    # A5
    for k, kt in (("K4_vs_K1_bce", "Bce"), ("K4_vs_K1_rankasl", "Rank"),
                  ("K4_vs_attn128_rankasl", "Wide")):
        t = an["A5_moe"]["AveragePrecision"][k]
        put(f"dkMoe{kt}Med", t.get("median_diff"), 4)
        put(f"dkMoe{kt}Win", t.get("wins_a"))
        put(f"dkMoe{kt}Loss", t.get("wins_b"))
        put(f"dkMoe{kt}P", None if t.get("p_holm") is None else fmt_p(t["p_holm"]))
        put(f"dkMoe{kt}N", t.get("n"))
    # A6: datasets (of those with reference learners) where some reference
    # learner beats every neural configuration, per metric
    a6 = an["A6_external"]
    for m, mt in mtag.items():
        n_ds, n_beaten = 0, 0
        names = []
        for ds in A.DATASETS:
            if ds not in a6:
                continue
            n_ds += 1
            confs = a6[ds]
            beaten = any(all(not confs[c][ext][m]["neural_better"] for c in confs)
                         for ext in next(iter(confs.values())))
            if beaten:
                n_beaten += 1
                names.append(DSN[ds])
        put(f"dkExtN{mt}", n_ds)
        put(f"dkExtBeaten{mt}", n_beaten)
        put(f"dkExtBeatenNames{mt}", ", ".join(names) if names else "none")
    # objective effect on the ten datasets NOT used by the pre-study screen
    screen = {"scene", "mscv2", "protein_pyrococcus"}
    for a in A.FIVE:
        b = A.seed_table(cells, a, "bce", "AveragePrecision")
        r = A.seed_table(cells, a, "rankasl", "AveragePrecision")
        other = [r[ds][0] - b[ds][0] for ds in b if ds in r and ds not in screen]
        put(f"dkObjOtherWin{tag[a]}", sum(1 for x in other if x > 0) if other else None)
        put(f"dkObjOtherN{tag[a]}", len(other) if other else None)
    if ext_counts:
        put("dkExtBeatenEnsAP", ext_counts["ens"])
        put("dkExtBeatenEnsNamesAP", ", ".join(ext_counts["ens_names"]) or "none")
        put("dkExtNAll", ext_counts["n"])
        put("dkExtBeatenSingleAll", ext_counts["single"])
        for g, gt in (("native", "Native"), ("framed", "Framed")):
            n, s1, e1, nm = ext_counts["groups"][g]
            put(f"dkExtN{gt}", n)
            put(f"dkExtSingle{gt}", s1)
            put(f"dkExtEns{gt}", e1)
            put(f"dkExtSingleNames{gt}", ", ".join(nm) or "none")
    put("dkNcells", an.get("n_cells"))
    body = header("analysis.json") + "\n".join(
        f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in sorted(M.items())) + "\n"
    write("gen_numbers.tex", body)


def main():
    an = json.load(open(os.path.join(CAMP, "analysis.json")))
    cells = A.load_units(CAMP)
    t_objective(an)
    t_architecture(an)
    t_ensemble(an)
    t_variance(an)
    t_moe(an)
    ext_counts = t_external(cells, an)
    t_external_full(an)
    t_effects_perdataset(cells, an)
    t_perdataset(cells, an)
    t_numbers(an, cells, ext_counts)
    print("tables written to", os.path.relpath(OUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
