#!/usr/bin/env python3
"""Pre-processing correction table (Section 'correction'), from the isolation study.

Design (PREREGISTERED.md, Addendum A): {transductive (shipped) bags, per-fold
leak-free bags} x {legacy 1e-6 std clamp, unit scale for constant-on-train
features}. LCGA + BCE, five seeds, CPU, same protocol as the campaign; the
(per-fold, unit) cell is the campaign itself. Reference learners: one run per
condition (deterministic apart from the k chosen on validation).

Emotions and Yeast have no constant-on-train features (checked on all folds),
so the clamp cannot act there and only the bag construction is varied.

Also emits the reference-learner values reported before this study for Medical,
which additionally carried the cumulative-normalisation bug of the old
reference-learner script.

Writes paper_prai/tables/gen_correction.tex and gen_correction_numbers.tex.
"""
import json
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ISO = os.path.join(ROOT, "results", "dmkd_campaign", "isolation")
CAMP = os.path.join(ROOT, "results", "dmkd_campaign")
SEEDS = [42, 123, 456, 789, 1024]
DSN = {"emotions": "Emotions", "yeast": "Yeast", "medical": "Medical"}
EXT = [("miml_knn", "\\textsc{Miml-kNN}", "Mimlknn"), ("mlknn_hausdorff", "ML-kNN", "Mlknn"),
       ("br_bagmean", "BR-LR", "Brlr")]
CONDS = ["leaky_clamp", "leaky_unit", "free_clamp", "free_unit"]


def lcga(ds, cond):
    vals = []
    for s in SEEDS:
        if cond == "free_unit":
            d = json.load(open(os.path.join(CAMP, f"miml_lcga__bce__seed{s}.json")))
            vals.append(d[f"{ds}/miml_lcga__bce/single"]["summary"]["AveragePrecision"][0])
        else:
            tag = "" if ds == "medical" else f"{ds}__"
            p = os.path.join(ISO, f"lcga_bce__{tag}{cond}__seed{s}.json")
            if not os.path.exists(p):
                return None
            vals.append(json.load(open(p))["summary"]["AveragePrecision"][0])
    return float(np.mean(vals)), float(np.std(vals, ddof=1))


def ext(ds, cond, model):
    if cond == "free_unit":
        path = os.path.join(CAMP, "external", f"external_baselines_{ds}.json")
    elif ds != "medical":
        path = os.path.join(ISO, "ext_leaky_unit_ey", f"external_baselines_{ds}.json")
    else:
        path = os.path.join(ISO, f"ext_{cond}", f"external_baselines_{ds}.json")
    if not os.path.exists(path):
        return None
    return json.load(open(path))[f"{ds}/{model}/single"]["summary"]["AveragePrecision"][0]


def main():
    rows, macros = [], []
    ctag = {"leaky_clamp": "LeakyClamp", "leaky_unit": "LeakyUnit",
            "free_clamp": "FreeClamp", "free_unit": "FreeUnit"}
    dtag = {"emotions": "Emo", "yeast": "Yeast", "medical": "Med"}
    for ds in ["emotions", "yeast", "medical"]:
        learners = [("LCGA (BCE)", "Lcga", lambda c, ds=ds: lcga(ds, c))] + \
                   [(lab, t, (lambda c, ds=ds, m=m: ext(ds, c, m))) for m, lab, t in EXT]
        for i, (label, mt, getter) in enumerate(learners):
            cells = []
            for c in CONDS:
                if ds != "medical" and c.endswith("clamp"):
                    cells.append("=")
                    continue
                v = getter(c)
                if v is None:
                    cells.append("--")
                    continue
                if isinstance(v, tuple):
                    cells.append(f"{v[0]:.3f} ({v[1]:.3f})")
                    v = v[0]
                else:
                    cells.append(f"{v:.3f}")
                macros.append(f"\\newcommand{{\\dkIso{mt}{dtag[ds]}{ctag[c]}}}{{{v:.3f}}}")
            rows.append(f"{DSN[ds] if i == 0 else ''} & {label} & " + " & ".join(cells) + " \\\\")
        if ds != "medical":
            rows.append("\\addlinespace")
    old = json.load(open(os.path.join(ROOT, "results", "preliminary", "external_baselines_medical.json")))
    for m, _, t in EXT:
        v = old[f"medical/{m}/single"]["summary"]["AveragePrecision"][0]
        macros.append(f"\\newcommand{{\\dkIsoOld{t}Med}}{{{v:.3f}}}")
    body = r"""%% GENERATED by scripts/dmkd_correction_table.py; do not edit numbers by hand.
\begin{table}[t]
\centering
\caption{Effect of the pre-processing corrections on Average Precision for the three $k$-NN-framed datasets. Columns cross the bag construction (transductive bags as shipped, or rebuilt per fold from the fitting split) with the feature scaling (legacy scale clamp at $10^{-6}$, or unit scale for features constant on the training rows). LCGA: mean (sd) over five seeds; reference learners: one run. On Emotions and Yeast no feature is constant on the training rows, so the two scalings coincide (``=''). The right-most column is the pipeline used for every other result in this paper.}
\label{tab:correction}
\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}ll cc cc@{}}
\toprule
 & & \multicolumn{2}{c}{Transductive bags} & \multicolumn{2}{c}{Per-fold bags} \\
\cmidrule(lr){3-4}\cmidrule(l){5-6}
Dataset & Learner & clamp & unit & clamp & unit \\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}
\end{table}
"""
    with open(os.path.join(ROOT, "paper_prai", "tables", "gen_correction.tex"), "w") as fh:
        fh.write(body)
    with open(os.path.join(ROOT, "paper_prai", "tables", "gen_correction_numbers.tex"), "w") as fh:
        fh.write("%% GENERATED by scripts/dmkd_correction_table.py\n" + "\n".join(macros) + "\n")
    print("\n".join(rows))


if __name__ == "__main__":
    main()
